### ISSUE TITLE
Iteration 0

### ISSUE THREAD

**Issue by yeseg11** [avicohen89/Music-Similarity#18]
#### TODO issues
- [x] #6  write proposal document.  
- [x] #7  send proposal document to Miriam. 
- [x] #9  Acedamic article regarding the technologies we are going to use in this project lifecycle.  
- [x] #10  Possible risks that may appear during the project lifecycle.
