### ISSUE TITLE
Iteration 1 - MVP

### ISSUE THREAD

**Issue by yeseg11** [avicohen89/Music-Similarity#19]
#### TODO issues
- [x] #1 learn MongoDB
- [x] #2 Research and discover what information can be extracted from YouTube API
- [x] #12 Research and discover what information can be extracted from MusicBrantz
- [x] #13 Research and discover what information can be extracted from last.fm
- [x] #11 define with which parameters our Recommendation system will work
- [x] #14 Decide with which database we will work
- [x] #3 find tracks by year
- [x] #22 Research and discover what information can be extracted from discogs.com
- [x] #5 fix how to get more then 100 track's from artist
- [x] #8 Use-cases, UML screens as planning procedure to the project
