### ISSUE TITLE
Iteration 2 Alpha

### ISSUE THREAD

**Issue by yeseg11** [avicohen89/Music-Similarity#20]
#### TODO issues

- [x] #4 numbers of likes by track.
- [x] #16 wrote tests are covering at least 70% of our code.
- [x] #26 write a Alpha report
- [x] #23 we should add link to YouTube and show it in new frame as attached to index page
- [x] #24 create short video about project and alpha iteration
- [x] #25 add documentation to code files
- [x] #27 add readme file to Alpha release
- [x] #15 have a usable recommendation and music similarity system with most of the features available.
- [x] #17 able to publish an alpha release.
